### ISSUE TITLE
none UTF8 character in javadoc comment

### ISSUE THREAD

**Issue by chriscamacho** [wnbittle/dyn4j#17]
[javac] /home/chris/development/SpritePlacer2/src/org/dyn4j/collision/manifold/ClippingManifoldSolver.java:47: error: unmappable character for encoding UTF8
    [javac]  * Uses Sutherland�Hodgman clipping to clip the closest features of the two {@link Convex} {@link Shape}s to obtain

Possibly as my build.xml treats warnings as errors? is there a javadoc UTF8 compatible way to express the included character?

**Comment by wnbittle** [comment]
Interesting.  That should be just a '-' character...

**Comment by chriscamacho** [comment]
looking via git hubs web view (of the source), it seems that a '–' character snook in instead of a '-' character...  –!=-  !!

**Comment by wnbittle** [comment]
ahh, I'll get that taken care of.  Are you trying to build the anode branch or master?

**Comment by chriscamacho** [comment]
I just pulled from the url on the github site and directly included the 
src folder in my project - so I assume its the master branch ?

**Comment by wnbittle** [comment]
Yeah, that's the master branch.  I've fixed this in the anode branch, which will soon (next few weeks or so) be merged into master.  anode has a good bit of breaking changes, so it's probably best to work of that.

**Comment by chriscamacho** [comment]
* Implementation of the GilbertJohnsonKeerthi (GJK) algorithm for collision detection.
just did a recent pull (you have been busy!)

**Comment by chriscamacho** [comment]
also...!
 * @see <a href="http://www.dyn4j.org/2010/04/gjk-gilbert-johnson-keerthi/" target="_blank">GJK (GilbertJohnsonKeerthi)</a>
 * @see <a href="http://www.dyn4j.org/2010/04/gjk-distance-closest-points/" target="_blank">GJK  Distance &amp; Closest Points</a>

**Comment by chriscamacho** [comment]
....and!
	 * @see <a href="http://www.dyn4j.org/2010/04/gjk-distance-closest-points/" target="_blank">GJK  Distance &amp; Closest Points</a>

**Comment by wnbittle** [comment]
doh!

**Comment by wnbittle** [comment]
Should all be taken care of now.
