### ISSUE TITLE
warnings caused by missing overrides

### ISSUE THREAD

**Issue by chriscamacho** [wnbittle/dyn4j#18]
even if you've no use for the overrides, should they not be at least empty methods ?
although the likes of hashcode could come in useful later...

    [javac] Compiling 209 source files to /home/chris/development/dyn4j-test/bin
    [javac] /home/chris/development/dyn4j-test/src/org/dyn4j/dynamics/Step.java:37: warning: [overrides] Class Step overrides equals, but neither it nor any superclass overrides hashCode method
    [javac] public class Step {
    [javac]        ^
    [javac] error: warnings found and -Werror specified
    [javac] /home/chris/development/dyn4j-test/src/org/dyn4j/dynamics/RaycastResult.java:39: warning: [overrides] Class RaycastResult overrides equals, but neither it nor any superclass overrides hashCode method
    [javac] public class RaycastResult implements Comparable<RaycastResult> {
    [javac]        ^
    [javac] /home/chris/development/dyn4j-test/src/org/dyn4j/dynamics/ConvexCastResult.java:37: warning: [overrides] Class ConvexCastResult overrides equals, but neither it nor any superclass overrides hashCode method
    [javac] public class ConvexCastResult implements Comparable<ConvexCastResult> {
    [javac]        ^
    [javac] /home/chris/development/dyn4j-test/src/org/dyn4j/geometry/AABB.java:47: warning: [overrides] Class AABB overrides equals, but neither it nor any superclass overrides hashCode method
    [javac] public class AABB implements Translatable {
    [javac]        ^
    [javac] /home/chris/development/dyn4j-test/src/org/dyn4j/dynamics/DetectResult.java:35: warning: [overrides] Class DetectResult overrides equals, but neither it nor any superclass overrides hashCode method
    [javac] public class DetectResult {
    [javac]        ^
    [javac] /home/chris/development/dyn4j-test/src/org/dyn4j/dynamics/Force.java:36: warning: [overrides] Class Force overrides equals, but neither it nor any superclass overrides hashCode method
    [javac] public class Force {
    [javac]        ^
    [javac] /home/chris/development/dyn4j-test/src/org/dyn4j/dynamics/Torque.java:35: warning: [overrides] Class Torque overrides equals, but neither it nor any superclass overrides hashCode method
    [javac] public class Torque {
    [javac]        ^
    [javac] /home/chris/development/dyn4j-test/src/org/dyn4j/BinarySearchTreeNode.java:36: warning: [overrides] Class BinarySearchTreeNode overrides equals, but neither it nor any superclass overrides hashCode method
    [javac] final class BinarySearchTreeNode<E extends Comparable<E>> implements Comparable<BinarySearchTreeNode<E>> {
    [javac]       ^
    [javac] /home/chris/development/dyn4j-test/src/org/dyn4j/Reference.java:38: warning: [overrides] Class Reference overrides equals, but neither it nor any superclass overrides hashCode method
    [javac] public class Reference<T> {
    [javac]        ^
    [javac] /home/chris/development/dyn4j-test/src/org/dyn4j/collision/CategoryFilter.java:93: warning: [overrides] Class CategoryFilter overrides equals, but neither it nor any superclass overrides hashCode method
    [javac] public class CategoryFilter implements Filter {
    [javac]        ^
    [javac] /home/chris/development/dyn4j-test/src/org/dyn4j/geometry/decompose/SweepLineEdge.java:40: warning: [overrides] Class SweepLineEdge overrides equals, but neither it nor any superclass overrides hashCode method
    [javac] final class SweepLineEdge implements Comparable<SweepLineEdge> {
    [javac]       ^
    [javac] 1 error
    [javac] 11 warnings

**Comment by wnbittle** [comment]
I've went though and cleaned this up some.  Using Eclipse it doesn't set the compiler to show these warnings.

Either way, I either removed the equals method or added the hashcode method.

**Comment by chriscamacho** [comment]
confirmed, thanks - btw I would recommend

>            <compilerarg value="-Werror" />
>            
>            <compilerarg value="-Xmaxerrs" />
>            <compilerarg value="1" />
>            <compilerarg value="-Xdiags:verbose" />

Not for pedantry - but rather because it's saved me later pain - plenty of times!
