### ISSUE TITLE
Sap.detect(aabb, filter) returns false when it should return true

### ISSUE THREAD

**Issue by schosin** [wnbittle/dyn4j#20]
I'm using Sap (and Sat) on their own. Every Collidable inside the Sap is a rectangle.
When I call Sap.detect(aabb) with aabb overlapping the rightmost Collidable inside the tree such that aabb.getMinX > rightmost.getMinX, Sap.detect returns false. The problem is that tree.ceiling ignores rightmost because of how SapProxy.compareTo is implemented.
The result is that the aabb will be able to collide with the left side of the rightmost rectangle, but will pass through its top, bottom and right side.

For now I switched to DynamicAABBTree, which works fine.

Greetings,
schosin

**Comment by wnbittle** [comment]
Ok, thanks for the report.  Do you have a test setup that I can use to reproduce?

**Comment by schosin** [comment]
Apart from reading Java, I haven't done anything with it lately. Here's a short, commented test written in Scala: http://pastebin.com/h7XMeCX2
Hopefully this helps.

**Comment by wnbittle** [comment]
Thanks for the sample, that did help.  I've fixed this in version 3.2.3 by using the custom BinarySearchTree in dyn4j and performing an appropriate search.
