### ISSUE TITLE
Wrong values returned from getRadius(Vector2) methods for Slice, Capsule, Ellipse, and HalfEllipse

### ISSUE THREAD

**Issue by wnbittle** [wnbittle/dyn4j#21]
Issue reported for Slice: http://forum.dyn4j.org/viewtopic.php?f=3&t=287

Investigation revealed that there was also an issue with the Capsule, Ellipse and HalfEllipse getRadius(Vector2) methods.

**Comment by wnbittle** [comment]
This was fixed in version 3.2.3

**Comment by TeamFinal** [comment]
Hello William,
in the org.dyn4j.geometry.HalfEllipse class in the getRadius method you say:

> in the half ellipse case, if the point is on the side of the flat edge
> then we do the ellipse code, else we can just return the farthest of the
> two points that make up the flat side

But this should be only true if the height isnt greater than half the width:

![image](https://user-images.githubusercontent.com/46204212/50497419-77bf1000-0a37-11e9-87ec-75c11f1ac91d.png)

Greetings
Andreas
