### ISSUE TITLE
How do I build this project.

### ISSUE THREAD

**Issue by yadavvi91** [wnbittle/dyn4j#25]
As the title of the issue says, how do I build this project? I am trying to make it as a `gradle project`, however, the `examples` wouldn't compile. My gradle file looks like this - 

    apply plugin: 'java'
    
    sourceCompatibility = 1.8
    
    repositories {
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
    }
    
    dependencies {
        compile 'org.dyn4j:dyn4j:3.2.3'
        compile 'org.jogamp.jogl:jogl-all:2.3.1'
        testCompile group: 'junit', name: 'junit', version: '4.12'
    }

I always get this error while building the project - 

    Error:(174, 21) java: cannot access com.jogamp.common.type.WriteCloneable
      class file for com.jogamp.common.type.WriteCloneable not found

**Comment by wnbittle** [comment]
I'm not familiar enough with grade to offer any advise there.  I build in eclipse.  I don't remember what version of JOGL I last built it with, but that may be the problem.  I've had to make minor changes whenever I update JOGL.

**Comment by yadavvi91** [comment]
Could you please mention the `jogl` version in the README file, I was trying to port it to `gradle` so that it would be easier to build in `Intellij Idea`

**Comment by wnbittle** [comment]
Ok, looking at this closer, I think you need to include the gluegen jars:

- gluegen.jar
- gluegen-rt.jar

You'll need the natives of gluegen and jogl if you want to run it.  2.3.1 is the version that I'm building against.  I will add to the Readme.

**Comment by yadavvi91** [comment]
Hey that works! My `build.gradle` for the `examples` module is like this - 

    version '3.2.3'

    apply plugin: 'java'

    sourceCompatibility = 1.8

    repositories {
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
    }

    dependencies {
        compile 'org.dyn4j:dyn4j:3.2.3'
        compile 'org.jogamp.gluegen:gluegen:2.3.1'
        compile 'org.jogamp.gluegen:gluegen-rt:2.3.1'
        compile 'org.jogamp.jogl:jogl-all:2.3.1'
        testCompile group: 'junit', name: 'junit', version: '4.12'
    }


Thanks!!
